from django.contrib import admin
from django.db import models


class Website(models.Model):
    link = models.TextField()
    UsingIP             = models.IntegerField() 
    LongURL             = models.IntegerField() 
    ShortURL            = models.IntegerField() 
    Symbol             = models.IntegerField() 
    Redirecting       = models.IntegerField() 
    PrefixSuffix       = models.IntegerField() 
    SubDomains          = models.IntegerField() 
    HTTPS               = models.IntegerField() 
    DomainRegLen        = models.IntegerField() 
    Favicon             = models.IntegerField() 
    NonStdPort          = models.IntegerField() 
    HTTPSDomainURL      = models.IntegerField() 
    RequestURL          = models.IntegerField() 
    AnchorURL           = models.IntegerField() 
    LinksInScriptTags   = models.IntegerField() 
    ServerFormHandler   = models.IntegerField() 
    InfoEmail           = models.IntegerField() 
    AbnormalURL         = models.IntegerField() 
    WebsiteForwarding   = models.IntegerField() 
    StatusBarCust       = models.IntegerField() 
    DisableRightClick   = models.IntegerField() 
    UsingPopupWindow    = models.IntegerField() 
    IframeRedirection   = models.IntegerField() 
    AgeofDomain         = models.IntegerField() 
    DNSRecording        = models.IntegerField() 
    WebsiteTraffic      = models.IntegerField() 
    PageRank            = models.IntegerField() 
    GoogleIndex         = models.IntegerField() 
    LinksPointingToPage = models.IntegerField() 
    StatsReport         = models.IntegerField() 
    pred_class          = models.IntegerField()
    score = models.FloatField(default=None)

class WebsiteAdmin(admin.ModelAdmin):
    list_display = ('link', 'HTTPS', 'UsingIP','AgeofDomain','GoogleIndex','pred_class','score')