# Generated by Django 3.2.13 on 2022-04-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('UsingIP', models.IntegerField()),
                ('LongURL', models.IntegerField()),
                ('ShortURL', models.IntegerField()),
                ('Symbol', models.IntegerField()),
                ('Redirecting', models.IntegerField()),
                ('PrefixSuffix', models.IntegerField()),
                ('SubDomains', models.IntegerField()),
                ('HTTPS', models.IntegerField()),
                ('DomainRegLen', models.IntegerField()),
                ('Favicon', models.IntegerField()),
                ('NonStdPort', models.IntegerField()),
                ('HTTPSDomainURL', models.IntegerField()),
                ('RequestURL', models.IntegerField()),
                ('AnchorURL', models.IntegerField()),
                ('LinksInScriptTags', models.IntegerField()),
                ('ServerFormHandler', models.IntegerField()),
                ('InfoEmail', models.IntegerField()),
                ('AbnormalURL', models.IntegerField()),
                ('WebsiteForwarding', models.IntegerField()),
                ('StatusBarCust', models.IntegerField()),
                ('DisableRightClick', models.IntegerField()),
                ('UsingPopupWindow', models.IntegerField()),
                ('IframeRedirection', models.IntegerField()),
                ('AgeofDomain', models.IntegerField()),
                ('DNSRecording', models.IntegerField()),
                ('WebsiteTraffic', models.IntegerField()),
                ('PageRank', models.IntegerField()),
                ('GoogleIndex', models.IntegerField()),
                ('LinksPointingToPage', models.IntegerField()),
                ('StatsReport', models.IntegerField()),
                ('pred_class', models.IntegerField()),
                ('score', models.FloatField(default=None)),
            ],
        ),
    ]
